feat: update task within milestone view
wondrous-dev/wondrous-frontend pull request #871
Opened 2022-08-12 04:00 UTC by juniusfree

**Demo** https://www.loom.com/share/37302e79ec774a73aa5267a954d9282a
**Task**: https://app.wonderverse.xyz/organization/wonderverse/boards?task=64109467886682768&view=grid&entity=task

**Changes**
1. feat: update task within milestone view
2. refactor: extract `TaskMenuStatus` to its own file component, reduce the required `props`
3. fix: filter is hidden with task is empty
4. style: fix eslint warnings, remove `index` folders with one exported function

2022-08-16 06:20 UTC, Lamperoyge requested changes
Nice! Left few comments

2022-08-16 06:20 UTC, Lamperoyge commented on wondrous-app/components/Common/MilestoneTask/MilestoneTaskList/index.tsx
> +  const hasProfileImage = assignee && assignee.profilePicture;
We can use optional chaining here? assignee?.profilePicture

2022-08-16 06:20 UTC, Lamperoyge commented on wondrous-app/components/Common/MilestoneTask/MilestoneTaskList/index.tsx
> +        const viewUrl = `/organization/${orgUsername || org?.username}/boards?task=${id}`;
I think this will work only for orgs, do we need to handle the viewUrl for pod level too?

2022-08-16 06:20 UTC, Lamperoyge commented on wondrous-app/components/Common/MilestoneTask/MilestoneTaskList/styles.tsx
> +  background-color: #171717;
can we use palette here too?

2022-08-16 06:20 UTC, Lamperoyge commented on wondrous-app/components/Common/MilestoneTask/index.tsx
> +  const limit = 10;
we can use LIMIT from services/board. It's set to 10 but in the future if we want to change it's easier to do it from one place 

`import { LIMIT } from 'services/board'`

2022-08-16 06:20 UTC, Lamperoyge commented on wondrous-app/components/Common/TaskMenuStatus.tsx
> +const taskProposalStatus = (task) => {
`import { getProposalStatus } from utils/board`

There's this function that takes in the task and the output is the status

2022-08-16 06:20 UTC, Lamperoyge commented on wondrous-app/components/Common/TaskMenuStatus.tsx
> +const statusesNonProposal = ({ task, entityType, canArchive }) => {
think we need a more explanatory name here, how about getProposalStatuses and getTaskStatuses ?

2022-08-25 02:16 UTC, terryli0095 approved these changes

2022-08-25 02:19 UTC, merged