initial draft for calendar view board
wondrous-dev/wondrous-frontend pull request #895
Opened 2022-08-19 12:40 UTC by pkmazarakis

2022-08-24 03:39 UTC, terryli0095 commented on wondrous-app/.env.development
> +NEXT_PUBLIC_GRAPHQL_SERVER_URL=http://localhost:4000/graphql
should revert this

2022-08-24 20:13 UTC, vefimov requested changes

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/CalendarView/styles.tsx
> +  border-right: 0.5px solid #343434;
better write it like 
```
border-style: solid;
border-width: 0 0.5px 1px 0.5px;
border-color: #343434;
```

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/CalendarView/styles.tsx
> +  padding-top: ${(props) => (props.view === 'WEEK' ? '8px' : '0px')};
`0px`, `px` is redundant

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/CalendarView/styles.tsx
> +  <TaskStatus status={props.status} style={{ width: '20px', height: '20px', marginRight: '8px' }} />
use styled-components styles instead of the inline styles

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/Common/Boards/index.tsx
> +  calendarFilters?: any;
write TS type

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/Common/Boards/index.tsx
> +  onCalendarDateChange?: any;
write TS type

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/Common/BoardsActivity/index.tsx
> +        board?.entityType === ENTITIES_TYPES.PROPOSAL ||
you can simplify this code and write 
```
[ENTITIES_TYPES.PROPOSAL, ENTITIES_TYPES.MILESTONE, ENTITIES_TYPES.BOUNTY].includes(board?.entityType)
```

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/organization/boards/boards.tsx
> +  onCalendarDateChange: ({}) => any;
write TS type

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/components/organization/boards/boards.tsx
> +  calendarFilters: any;
write TS type

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/pages/organization/[username]/boards.tsx
> +        return;
you don't need `return`

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/pages/pod/[podId]/boards.tsx
> +        return;
you don't need `return `

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/pages/pod/[podId]/boards.tsx
> +  const firstDay = new Date(now.getFullYear(), now.getMonth(), 1);
use `date-fns` and `startOfMonth` function

2022-08-24 20:13 UTC, vefimov commented on wondrous-app/pages/pod/[podId]/boards.tsx
> +  const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0);
use `date-fns` and `endOfMonth` function

2022-08-24 20:14 UTC, vefimov commented
Please use palette for colors

2022-08-25 05:22 UTC, andywong418 requested changes
Couple of thoughts here:
- let's add some screen recordings of the feature here since it's a large feature, or at least screenshots
- `http://localhost:3000/dashboard?view=calendar` complete fails to load for me
- We should aim to test the code written rigorously before PR - I found some bugs on the backend that would have caused errors
- I think there's also a rebasing error in `organization/wrapper/wrapper.tsx` that causes none of the pages to load.
- build failing on an open PR should not be happening

2022-08-25 05:22 UTC, andywong418 commented on wondrous-app/components/CalendarView/index.tsx
> +        calendarFilters.statuses?.length > 0
calendarFilters needs to be null checked `calendarFilters?.statuses?.length

2022-08-25 05:22 UTC, andywong418 commented on wondrous-app/components/organization/wrapper/wrapper.tsx
> +import LinkedInIcon from '../../Icons/linkedIn';
This file seems to be a mess - there may be some rebasing issues

2022-08-26 16:31 UTC, Lamperoyge requested changes

2022-11-26 20:48 UTC, closed without merging