adding snackbar when submission successfully added
wondrous-dev/wondrous-frontend pull request #904
Opened 2022-08-23 10:39 UTC by pkmazarakis

2022-08-23 15:40 UTC, terryli0095 commented
i think we should potentially do this on 'onComplete', because if there's an error, this will still show

2022-08-23 18:05 UTC, andywong418 commented
Agree with @terryli0095 but looks good otherwise. Please also merge to staging instead

2022-08-24 04:00 UTC, terryli0095 requested changes

2022-08-24 04:00 UTC, terryli0095 commented on wondrous-app/components/Common/TaskSubmission/submissionForm.tsx
> +    setSnackbarAlertMessage(`Successfully submitted!`);
i think moving this to onComplete makes more sense

2022-11-17 01:28 UTC, merged